default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: mixed-line-ending
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    - id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.17.0
    hooks:
    - id: pyupgrade
      args: ['--py36-plus']
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    - id: remove-tabs
    - id: remove-crlf
