default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: mixed-line-ending
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    - id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.26.2
    hooks:
    - id: pyupgrade
      args: ['--py36-plus']
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    - id: remove-tabs
