name: CI
on:
  push:
    branches: [master]
    tags: ['*']
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [py36, py37, py38]
        os: [windows-latest, ubuntu-latest]
        include:
          - name: py36
            python-version: 3.6
            tox: py36
          - name: py37
            python-version: 3.7
            tox: py37
          - name: py38
            python-version: 3.8
            tox: py38

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
    - name: install abserde
      run: python -m pip install .
    - name: install tox
      run: python -m pip install tox
    - name: install multiclass for tests
      run: python -m abserde examples/multiclass.pyi
    - name: run tests
      run: python -m tox -e ${{ matrix.tox }}
